Feature/initialsetting
wecode-bootcamp-korea/47-1st-SujeongGwa-backend pull request #1
Opened 2023-06-26 11:05 UTC by Teachsue

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
-> 간단한 get  메소드를 통하여 우리의 데이터베이스가 통신이 되는가를 확인하였다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
-> 정상적인 통신을 확인하여, 서버의 안정성을 확보하였다. 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

-> 초기 환경세팅

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 서버가 어떻게 구성되며, 돌아가는지 확인하였다.
-

2023-06-26 11:18 UTC, Kang-kyunghun requested changes

2023-06-26 11:18 UTC, Kang-kyunghun commented on app.js
> +});
dataSource.js로 분리 해주세요.

2023-06-26 11:18 UTC, Kang-kyunghun commented on app.js
> +    })
server가 실행 될 때 동작할 수 있게 수정해 주세요.

2023-06-27 01:34 UTC, kyeongraekim requested changes

2023-06-27 01:34 UTC, kyeongraekim commented on models/dataSource.js
> +  type: 'mysql',
- 해당 내용은 환경변수로 관리하지 않는 이유가 있으실까요?

2023-06-27 01:34 UTC, kyeongraekim commented on db/migrations/20230626095025_create_user_table.sql
> +CREATE TABLE user (
- 단 한 건의 마이그레이션 파일이 함게 올라와있네요! 해당 내용 깃 캐시 삭제 이후재 푸시해주세요!

2023-06-27 08:11 UTC, kyeongraekim approved these changes
LGTM!~

2023-06-27 08:11 UTC, merged