[47기 이주현] ADD: POST ORDER
wecode-bootcamp-korea/47-1st-SujeongGwa-backend pull request #13
Opened 2023-06-30 10:10 UTC by sioscorial

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
장바구니에서 주문서로 넘어갈때 안에 들어가도록 하였습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
merge됨으로써 유저가 장바구니에서 구매완료시 구매확정된거를 확인할 수 있게 됩니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

carts에 담겨져있는 user_id와 product_id와 quantity를 가져와서
해당 product_id를 통해 products에 들어가서 각 products의 price와 weight를 
가져와서 총합 가격과 총합 무게를 구할 수 있게 구현하였으며,
uuid를 사용해서 랜덤 한 주문번호를 가지게 하였으며
프런트에서 address를 받으면 그거를 같이 넣게 구현하였습니다.
<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

![image](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/131604960/d9776d59-180e-4d7c-841d-f01f8d1876fe)

![image](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/131604960/f9555834-05b7-4479-bf4e-bdb93cd74390)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

여러개의 테이블에서 가지고 와서 사용하는걸 처음해봤는데 아직 다는 이해하지 못하였다.
uuid도 처음 써봤는데 생각보다 사용하는게 쉬워서 나중에도 잘 이용할것 같다..

  <br />

2023-07-04 02:12 UTC, Kang-kyunghun requested changes

2023-07-04 02:12 UTC, Kang-kyunghun commented on app.js
> +const PORT = process.env.PORT;
해당 부분은 왜 수정 하셨나요? default port를 지정해 두는 것은 좋은 방법입니다.

2023-07-04 02:12 UTC, Kang-kyunghun commented on controllers/orderController.js
> +    await orderService.createOrder(userId, address);
```suggestion
  try {
    const userId = req.user;
    const { address } = req.body;
    
    await orderService.createOrder(userId, address);
```

2023-07-04 02:12 UTC, Kang-kyunghun commented on controllers/userController.js
> +    const { type_id, name, email, password, account } = req.body;
왜 다시 스네이크 케이스인가요?

2023-07-04 02:12 UTC, Kang-kyunghun commented on models/orderDao.js
> +      [user_id]
1. '*' 사용은 지양해 주세요.
2. 장바구니에 있는 제품은 무조건 전체 구매인가요?

2023-07-04 02:12 UTC, Kang-kyunghun commented on services/orderService.js
> +    }
해당 로직이 dao에도 있던데 확인해 주세요.

2023-07-04 02:12 UTC, Kang-kyunghun commented on models/orderDao.js
> +const createOrder = async (user_id, address) => {
user point 확인, cart 확인 제품 확인은 service에서 로직 처리 해주세요.

2023-07-04 03:14 UTC, sioscorial commented on models/orderDao.js
> +      [user_id]
저희 기획상 장바구니에 있는 물품들은 다 전체 구매로 되어있어서 
장바구니를 다 가져왔습니다

2023-07-04 06:55 UTC, Kang-kyunghun requested changes

2023-07-04 06:55 UTC, Kang-kyunghun commented on controllers/userController.js
> +    if (type_id !== 1 && !account) {
해당 수정 사항이 한 두번이 아닌 것 같은데, push 하고 fileChanged 확인 안 하시나요?
```suggestion
    if (typeId !== 1 && !account) {
```

2023-07-04 06:55 UTC, Kang-kyunghun commented on models/orderDao.js
> +    const order_status_id = 1;
```suggestion
    const orderNumber = uuid.v4();
    const orderStatus_id = 1;
```

2023-07-04 06:55 UTC, Kang-kyunghun commented on models/orderDao.js
> +
주문한 상품 데이터 넣는 로직이 없네요. 추가해 주세요.

2023-07-04 06:55 UTC, Kang-kyunghun commented on models/orderDao.js
> +const calculatePrice = async (userId, carts) => {
해당 함수가 왜 필요하죠?
코멘트로 남겨주세요.

2023-07-04 06:55 UTC, Kang-kyunghun commented on models/userDao.js
> +    return [userId];
```suggestion
    return user;
```

2023-07-04 06:55 UTC, Kang-kyunghun commented on services/orderService.js
> +    if (carts.length === 0) {
```suggestion
    const carts = await orderDao.getCarts(userId);
    
    if (carts.length === 0) {
```

2023-07-04 06:55 UTC, Kang-kyunghun commented on services/orderService.js
> +    }
해당 계산은 cart에서 가져온 정보로 충분히 할 수 있습니다. 개선해 주세요.

2023-07-04 06:55 UTC, Kang-kyunghun commented on services/userService.js
> +  const accessToken = jwt.sign({ email: user.email }, process.env.JWT_SECRET, {
왜 다시 email로 바뀌였나요?

2023-07-04 06:55 UTC, Kang-kyunghun commented on services/userService.js
> +    { account: accountUser[0][0].account },
여기도 마찬가지로 왜 바뀌였죠?

2023-07-05 07:54 UTC, Kang-kyunghun requested changes

2023-07-05 07:54 UTC, Kang-kyunghun commented on models/cartDao.js
> +  ]);
1. Promise.all을 사용하는 상황이 압니다. 제거해 주세요.
2. cartItem을 불러오는 곳에서 []로 감싸게 되면 여러 데이터 중 1개만 가져오게 됩니다. 

```suggestion
const getCarts = async (userId) => {
  const cartIemts = await dataSource.query(
      `SELECT 
        carts.product_id,
        products.id,
        products.price,
        products.weight,
        carts.quantity 
      FROM 
        carts
      JOIN
        products
      ON
        carts.product_id = products.id
      WHERE 
        user_id = ?`,
      [userId]
    );
```

2023-07-05 07:54 UTC, Kang-kyunghun commented on models/cartDao.js
> +};
```suggestion
  return cartItems
};
```

2023-07-05 07:54 UTC, Kang-kyunghun commented on models/orderDao.js
> +    }
아까 리뷰 주었듯이 쿼리가 여러번 호출하는 것이 아닌 쿼리가 1번만 호출 될 수 있도록 해주세요.
(bulk insert 구현)

2023-07-05 07:54 UTC, Kang-kyunghun commented on services/orderService.js
> +    );
reduce가 필요한가요?

2023-07-05 07:54 UTC, Kang-kyunghun commented on services/orderService.js
> +    });
1. map 안에서는 값 계산만 해주세요.
2. map 안에서는 scope가 달라집니다. map 밖에서 let으로 totalPrice, totalWeht를 선언해 주세요.
3. 이를 다시 구현 하시면 아래 reduce는 필요하지 않을 겁니다.
```suggestion
    const cartItems = carts.map((cart) => {
      const price = cart.price;
      const weight = cart.weight;
      const quantity = cart.quantity;
      const totalPrice = price * quantity;
      const totalWeight = weight * quantity;

      if (userPoint < totalPrice) {
        const error = new Error('Not enough points to complete this purchase');
        error.statusCode = 400;
        throw error;
      }
      return {
        price,
        weight,
        quantity,
        totalPrice,
        totalWeight,
      };
    });
```

2023-07-06 02:04 UTC, merged