[47기 정성남] ADD : 상품 필터링
wecode-bootcamp-korea/47-1st-SujeongGwa-backend pull request #17
Opened 2023-07-03 02:10 UTC by jseongnam

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  (예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  (예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

(예시) 로그인 기능 추가

- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
  블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
  <br />

2023-07-03 02:13 UTC, jseongnam commented
본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고,
사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
고객이 상품 필터링이 되어서 볼 수 있도록 구현하였습니다.
내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
(예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.

이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.
상품 주소 추출
개발한 화면을 캡쳐해서 첨부 해 주세요.
(drag & drop 또는 첨부파일 추가)
![image](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/105405028/5310df93-cf75-4f21-85d4-2d55121ae9e9)
![image](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/105405028/f30475d0-6a39-4871-8243-6b232ba0af02)

이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.
코드를 정밀하게 짜는 연습을 할 수 있었습니다.

2023-07-03 02:49 UTC, jseongnam commented
![image](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/105405028/7f0173d9-1b83-4238-b8c7-ae3579b2832e)
수정했습니다.

2023-07-03 03:23 UTC, jseongnam commented
수정사항 적용했습니다.

2023-07-03 06:15 UTC, kyeongraekim requested changes

2023-07-03 06:15 UTC, kyeongraekim commented on models/goodsDao.js
> +                SELECT *
- SELECT 문 내부 전체 컬럼을 명시해서 제 3의 개발자들도 해당 어플리케이션 단 코드를 통해서 어떠한 상세 데이터들을 goods의 영역에서 사용가능한지 명시해주세요!

2023-07-03 06:15 UTC, kyeongraekim commented on models/goodsDao.js
> +const goodsDao = async(category_id) => {
- category_id를 node.js javascript 컨벤션에 맞게 camelCase로 수정해주세요!

2023-07-03 06:15 UTC, kyeongraekim commented on models/goodsDao.js
> +        }
- 상기 코드를 아래와 같이 깔끔하게 수정해주세요!
- category_id에 대한 예외 처리를 DAO에서 하게 된다면, 추후 확장성이 확보가 되지 않는 코드처럼 보여집니다.
    - 언제든 카테고리 아이디가 늘어날 수도 있고, 때로는 변경될 수도 있기 때문이지요!
- 즉 데이터베이스내 없는 카테고리 pk 값에 대한 select문을 호출한다면, 결과론적으로 빈배열 등이 나올 예정입니다.
- 작성해주신것처럼 사전 예외처리가 아닌 해당 내용이 빈배열로 나왔을 때의 사후 예외처리로서 접근하시는 것을 권장드립니다.

```suggestion
const goodsDao = async(category_id) => {
    try{
            result = await appDataSource.query(
                `
                SELECT 
                   id,
                   name,
                   ... 이하 생략
                FROM products
                WHERE products.sub_category_id = ?
                `,[category_id]
                )

```

2023-07-03 06:15 UTC, kyeongraekim commented on models/goodsDao.js
> +        const result = await appDataSource.query(
-  다시 한번 상품의 상세 정보를 담는 변수명처럼 보여지는데 셀렉트문에 해당되는 컬럼 데이터는 이미지 url 밖에 담겨있지 않아 보입니다. 아래를 수정하거나, 해당 변수명을 수정해주세요!

2023-07-03 06:15 UTC, kyeongraekim commented on models/goodsDao.js
> +const goodsDao = async(category_id) => {
- 또한 변수명의 기준점을 드러내는 것이 권장됨으로, goodsDaoByCategoryId 정도로 수정해도 더 명확한 변수 표현법이 되겠네요!

2023-07-03 06:15 UTC, kyeongraekim commented on pull_data.js
> +      username: process.env.DB_USERNAME,
- 해당내용은 로컬에서 성남님이 개인의 목적으로 작성하신 데이터 기입 코드처럼 보여집니다. 해당 내용은 깃헙에서 공유를 하지마시고 깃이그노어에 추가하여서 개인의 차원에서만 유지관리를 해주세요!

2023-07-03 06:15 UTC, kyeongraekim commented on services/goodsService.js
> +    }catch(err){
- 해당 서비스 문에는 try-catch문이 필요없을 것 같습니다.
- 컨트롤러단에서의 또는 Dao 단에서의 catch가 작동할 예정이니 별도의 로직이 없는 서비스는 간단하게 return문만 작성해주세요!

2023-07-03 06:15 UTC, kyeongraekim commented on services/goodsService.js
> +    }catch(err){
- 해당 서비스 문에는 try-catch문이 필요없을 것 같습니다.
- 컨트롤러단에서의 또는 Dao 단에서의 catch가 작동할 예정이니 별도의 로직이 없는 서비스는 간단하게 return문만 작성해주세요!

2023-07-03 08:19 UTC, jseongnam commented
수정사항 적용했습니다.

2023-07-04 03:18 UTC, Kang-kyunghun commented
JS의 기본 컨벤션은 카멜케이스 입니다. 
전부 변경해 주세요.

2023-07-04 07:38 UTC, jseongnam commented
피드백 사항 수정했습니다.

2023-07-04 07:39 UTC, jseongnam commented
피드백 사항 수적했습니다.

2023-07-05 03:13 UTC, kyeongraekim requested changes

2023-07-05 03:13 UTC, kyeongraekim commented on models/goodsDao.js
> +            //result : 상품들을 goodsDaoByCategoryId 에 따라 분류한 query
- 불필요한 콘솔로깅을 제거해주세요!

2023-07-05 06:59 UTC, kyeongraekim approved these changes
LGTM!~

2023-07-05 06:59 UTC, merged