[47기 정성남] ADD : cart patch and del 수정
wecode-bootcamp-korea/47-1st-SujeongGwa-backend pull request #19
Opened 2023-07-03 04:38 UTC by jseongnam

수정사항 적용했습니다.

2023-07-03 06:03 UTC, kyeongraekim requested changes

2023-07-03 06:03 UTC, kyeongraekim commented on models/cartDao.js
> +    throw error;
- 해당 내용은 이미 auth.js 인가과정에서 유저 유무를 따져 걸러낼 수 있는 내용입니다.
- Dao에서 굳이 중복의 에러처리를 할 필요가 없을 것 같아 보이네요!

2023-07-03 06:03 UTC, kyeongraekim commented on controllers/cartController.js
> +    const users = req.user;
- 해당 변수에는 단일 회원의 정보가 담길 것임으로 users라는 복수보다 단수의 변수명을 설정해주세요!

2023-07-03 06:03 UTC, kyeongraekim commented on models/cartDao.js
> +            throw error;
- quantity가 0개로 되어 있는 부분을 에러 메세지에 담아서 보내주셔야 합니다.
- 해당 내용은 console을 찍는 행위임으로 에러 객체에 새롭게 메세지를 담는 행위는 아님을 말씀드립니다.
- Console을 찍는 행위란, 백엔드 서버단에서 에러가 났을 때 백엔드 자체적으로 로깅을 확인하기 위해 체크하는 행위입니다.

2023-07-03 06:03 UTC, kyeongraekim commented on models/cartDao.js
> +        }else{
- 위 if 문을 단문의 조건절로 처리하여도 무방해보입니다.
- 아래 29번라인부터의 로직을 else로 분기하지말고 진행해주세요!

2023-07-03 06:03 UTC, kyeongraekim commented on models/cartDao.js
> +        let cart_patch = ``;
- cart_patch는 파이썬등에 어울리는 스케이크 케이스이며, 현재 해당 모듈에서 빈 문자열의 변수선언이 불필요한 로직처럼 보여지네요!
- cart_patch의 렛을 이용한 변수선언은 생략해주셔도 될 것 같습니다.

2023-07-03 08:04 UTC, jseongnam commented
수정사항 적용했씁니다.

2023-07-05 03:17 UTC, kyeongraekim requested changes

2023-07-05 03:17 UTC, kyeongraekim commented on controllers/cartController.js
> +  const { user_id, product_id, quantity } = req.body;
- body에서 전달될 떄 camelCase로 프론트와 주고 받으면 해당 변수명을 스케이크 케이스에서 camel case로 올바르게 변경할 수 있겠네요!

2023-07-05 03:17 UTC, kyeongraekim commented on models/cartDao.js
> +            console.error("0개 미만으로는 숫자를 변경할 수 없습니다.",error)
- 해당 console.error는 콘솔 에러를 찍는 행위이며, 클라이언트에게는 전달되지 못할 메세지 입니다.
- 따라서 콘솔 에러로깅이아닌 실제 전달 가능한 에러메세지로서, invalid_request / invalid_request_quantity 정도의 메세지를 리스폰스할 수 있게 변경되면 좋을 것 같네요!

2023-07-05 03:17 UTC, kyeongraekim commented on models/cartDao.js
> +      let cart_patch = await dataSource.query(
- 이후 cart_patch 이후의 로직에서 해당 변수를 건들지 않음으로 (추가 변수 업데이트 로직이 없음으로), let이 아닌 const 문법으로 해당 변수를 선언해주세요!

2023-07-05 04:44 UTC, jseongnam commented
수정사항 적용했습니다.

2023-07-05 07:03 UTC, kyeongraekim commented on models/cartDao.js
> +        }
아래의 내용처럼 수정을 고려해주세요! 이전 리뷰 내용이 미반영상태처럼 보여집니다~

```suggestion
const patchProductsInCart = async(user_id,product_name, quantity)=>{
    try{
        if(quantity == 0){
            const error = new Error("INVALID QUANTITY REQUEST")
            error.statusCode = 400;
            throw error;
        }
```

2023-07-05 07:45 UTC, kyeongraekim approved these changes

2023-07-05 07:45 UTC, merged