ADD : dbmate
wecode-bootcamp-korea/47-1st-SujeongGwa-backend pull request #2
Opened 2023-06-27 12:06 UTC by Teachsue

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

데이터베이스를 기반으로 스키마를 작성하였으며, 이로 인하여 DB의 낭비 없이 효율적으로 고객의 데이터베이스를 관리 할 수 있게 되었다. 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

- 테이블 명
* types
* categories
* users
* products
* carts
* orders
* order_detail
* surface_type
* order_status
* sub_categories

-> 데이터베이스에 기반에 해당하는 테이블들을 만들었다.

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

![image](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/131442242/b120bc31-2144-41eb-a456-05add1686e0a)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.
-> DBmate up을 한번에 모든 테이블들을 올리려다가, 참조 오류가 발생하여 해결법을 찾다가, 외래키 관계가 있는 경우에는 참조를 신경써서 데이터를 동기화 하여 올려야 하는 점을 알게 되었다.

2023-06-27 14:32 UTC, Kang-kyunghun requested changes

2023-06-27 14:32 UTC, Kang-kyunghun commented on db/migrations/20230627114610_create_products_table.sql
> +  surface_type_id VARCHAR(50) NOT NULL,
- 데이터 타입 변경
- FOREIGN KEY 추가
```suggestion
  surface_type_id INT NOT NULL,
```

2023-06-27 14:32 UTC, Kang-kyunghun commented on db/migrations/20230627115454_create_orders_table.sql
> +  order_number INT NOT NULL,
- order_number 데이터는 UUID를 사용해 주고 해당 데이터는 VARCHAR로 저장해 주세요.
```suggestion
  order_number VARCHAR(100) NOT NULL,
```

2023-06-27 14:32 UTC, Kang-kyunghun commented on db/migrations/20230627115617_create_order_detail_table.sql
> +  products_id INT NOT NULL,
FOREIGN KEY 추가해 주세요.

2023-06-27 16:50 UTC, Teachsue commented on db/migrations/20230627115454_create_orders_table.sql
> +  order_number INT NOT NULL,
UUID 참고 자료

https://kotlinworld.com/417#JavaScript%--UUID%--%EB%A-%-C%EB%--%A-%EA%B-%B-

2023-06-27 17:00 UTC, Teachsue commented on db/migrations/20230627115617_create_order_detail_table.sql
> +  products_id INT NOT NULL,
오전 확인사항
products 테이블에서 id값 연결해오는 외래키 추가

2023-06-28 01:53 UTC, Kang-kyunghun requested changes
app.js에서 conflict가 났는데, 확인해 주세요.

2023-06-28 01:53 UTC, Kang-kyunghun commented on app.js
> +const uuid = uuidv4();
app.js에서 uuid는 필요 없습니다. 
제거해 주세요.
(나중에 service에서 사용될 예정)

2023-06-28 03:49 UTC, merged