[47기 서동희] ADD:signup 기능 추가
wecode-bootcamp-korea/47-1st-SujeongGwa-backend pull request #4
Opened 2023-06-29 03:49 UTC by donghee9

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
저희는 제품을 구매를 원하는 고객을 개인 법인사업자 개인사업자로 구분하여 기획하였습니다 . 개인의 경우에는 이름 이메일 비밀번호를 입력값 필수로 넣었으며, 사업자의 경우에는 account라는 계정을 추가하여 사업자 번호를 추가로 필수 입력값으로 받게 되었습니다 
고객의 타입을 따로 구분하여 관리하기 위해 types테이블을 만들어 데이터를 따로 저장하고 관리하며, 그 type_id 값에 따라 필수 입력값을 다르게 설정하였습니다 

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
고객의 타입에 따라 (법인사업자, 개인사업자, 개인) 관리하므로 고객도 타일의 쓰임에 따라 다르게 로그인 할수 있으며  결제 추후에 세금계산서 발급이나 , 영수증 발급이 용이합니다 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

(예시) 로그인 기능 추가

- email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- password 소문자 ,대문자, 특수문자,숫자 총 8자리이상 유효성 검사 추가
- user의 type_id(1->개인, 2->법인사업자 ,3->개인사업자)에 따라 받아야하는 필드를 다르게 지정함

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

1.타입이 1인경우 (개인유저인경우)
![스크린샷 2023-06-29 오후 12 39 16](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/129722492/1a4b0213-30cc-4ec3-8113-a328a0d47287)

2-1.타입이 2또는 3인 경우 (사업자인경우)
![스크린샷 2023-06-29 오후 12 41 10](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/129722492/ca3ee312-515d-490a-8cff-31c4e0a3ebf8)

2-2(예외처리)
![스크린샷 2023-06-29 오후 12 42 36](https://github.com/wecode-bootcamp-korea/47-1st-SujeongGwa-backend/assets/129722492/3183aeef-0ea7-4c06-8e43-e9bb9c46f5b0)

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- password 길이를 bcrypt를 사용하여 암호화하면 60자리가 되는데 varchar(50)으로 설정해서 input 값이 잘못되었다고 오류가 계속 되었다 앞으로는 ERD를 구축할때 여러가지 면을 고려해서 설계해야한다는 걸 알게 되었다  
-유저의 타입을 여러가지로 했을 때 각각의 유저에 대한 API를 설계해야하는건지 많은 고민을 했는데, 결국에 받는값이 다른거고, 동작하는 흐름을 같다는 결론하에 하나의 API로 여러가지 유저의 정보를 관리 할수 있게 되었다
  <br />

2023-06-29 07:27 UTC, kyeongraekim requested changes

2023-06-29 07:27 UTC, kyeongraekim commented on controllers/userController.js
> +            3: ["name", "email", "password", "account"],
type 2와 3이 중복되어 보이는데 다른 종류의 회원 유형의 가입이실까요?

2023-06-29 07:27 UTC, kyeongraekim commented on db/migrations/20230628155650_create_users_modifiypassword_table.sql
> +ALTER TABLE users MODIFY COLUMN password VARCHAR(100) NOT NULL;
- 비밀번호는 200자 정도로 넉넉히 설정해주세요!
- 선택하시는 해쉬 알고리즘에 따라서 그 비밀번호의 길이가 많이 늘어날수도 더 줄어들 수도 있음을 기억해주세요!

2023-06-29 07:27 UTC, kyeongraekim commented on controllers/userController.js
> +        return res.status(err.statusCode || 500).json({ message: err.message });
- 해당 API 로직이 진행되다가 내가 의도하지 않은 에러가 났을 경우에 해당 에러는 우리가 의도하지 않은 디테일한 에러의 사유를 다 담아서 클라이언트에게 노출할 수도 있습니다.
- 입력을 담당하는 컨트롤러에서 올바른 데이터가 들어오지 않아서 발생한 에러로서 해당 내용을 치환해주세요!

```javascript
        return res.status(err.statusCode || 500).json({ message: INVALID_USER_REQUEST });

2023-06-29 08:05 UTC, donghee9 commented on controllers/userController.js
> +            3: ["name", "email", "password", "account"],
네 다른 종류의 회원가입니다 
2:법인사업자
3:개인사업자 
입니다

2023-06-30 02:55 UTC, Kang-kyunghun requested changes

2023-06-30 02:55 UTC, Kang-kyunghun commented on app.js
> +        .initialize()
간격이 늘어났네요?

팀원들과 같은 간격을 유지해 주세요.(참고로 JS는 줄바꿈 시에 2칸을 원칙으로 합니다.)
팀원들 간에 같은 포멧을 유지할려면 pritter 사용을 권장 드립니다.

2023-06-30 02:55 UTC, Kang-kyunghun commented on controllers/userController.js
> +        const requiredFields = {
회원가입 로직은 오늘 오후에 저랑 구두로 만나서 이야기 해보셔야 할 것 같습니다.

2023-06-30 06:36 UTC, Kang-kyunghun requested changes

2023-06-30 06:36 UTC, Kang-kyunghun commented on controllers/userController.js
> +        }
타입이 1이 아닐 때도 이름이나 비밀번호는 필요한거 아닌가요?
```suggestion
          if (!name || !email || !password) {
              const error = new Error("KEY_ERROR: Missing required fields: name, email, password.");
              error.statusCode = 400;
              throw error;
          }
        }
        
        if (type_id !==1 && !account) {
            const error = new Error("KEY_ERROR: Missing required field.");
            error.statusCode = 400;
            throw error;
        }
     }
```

2023-07-02 12:08 UTC, merged